{% set version = "3.1.5" %}

package:
  name: mpfr
  version: {{ version }}

source:
  fn: mpfr-{{ version }}.tar.bz2                                                                        # [unix]
  url: http://ftp.gnu.org/gnu/mpfr/mpfr-{{ version }}.tar.gz                                            # [unix]
  sha256: f4eb5070883aee3fd8b927751ea63ff95aebe24418cde852439ce74c3dd2513c                              # [unix]
  fn: {{ commit }}.zip                                                                                  # [win]
  url: https://github.com/isuruf/mpfr/releases/download/{{ version }}-win/mpfr-{{ version }}-win.zip    # [win]
  sha256: 179d0e3de99926d4eee726ef1ee9daa6ccc44301572954702c6c3544bb3d8667                              # [win]

build:
  number: 1
  features:
    - vc14            # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain3
    - m4              # [unix]
    - libtool         # [unix]
    - gmp             # [unix]
    - vc 14           # [win]
    - mpir            # [win]
  run:
    - gmp             # [unix]
    - mpir            # [win]
    - vc 14           # [win]

test:
  commands:
    - if not exist %LIBRARY_INC%\\mpfr.h exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\mpfr_static.lib exit 1       # [win]
    - test -f ${PREFIX}/lib/libmpfr.a                          # [unix]
    - test -f ${PREFIX}/lib/libmpfr.dylib                      # [osx]
    - test -f ${PREFIX}/lib/libmpfr.so                         # [linux]

about:
  home: http://www.mpfr.org/
  license: LGPL 3
  license_file: {{ SRC_DIR }}/COPYING.LESSER
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
