{% set version = "4.1.1.rc1" %}

package:
  name: mpfr
  version: {{ version }}

source:
  url: https://www.mpfr.org/mpfr-{{ ".".join(version.split(".")[:3]) }}/mpfr-{{ version.replace(".rc", "-rc") }}.tar.gz
  sha256: ecb2045d9cab07290c02a5a70a37f0be822f679b3ba276628e2a6ba08cf97295

build:
  number: 0
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("mpfr") }}

requirements:
  build:
    - libtool         # [unix]
    - m4              # [unix]
    - make            # [unix]
    - gnuconfig       # [unix]
    - {{ compiler('c') }}
    - autotools_clang_conda  # [win]
  host:
    - gmp             # [unix]
    - mpir            # [win]

test:
  requires:
    - {{ compiler('c') }}
    - libtool         # [unix]
    - m4              # [unix]

  commands:
    - if not exist %LIBRARY_INC%\\mpfr.h exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1              # [win]
    - test -f ${PREFIX}/lib/libmpfr${SHLIB_EXT}                # [unix]

about:
  home: http://www.mpfr.org/
  license: LGPL-3.0-only
  license_file: {{ SRC_DIR }}/COPYING.LESSER
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
    - marcelotrevisani
