appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: l2xu+g7A8IOlyhsq6BXTFX3w24PJCdEPq9pOw28wUu8sN7g/U2qDkyDLsQkHN0AenTcuBIxVvJupRY1/afXQapsBqC6WbYMtXmIPrc3hw9oXUTF0tlOWeP5glLGqHi1FZaGIPmait+QtY2RWd1gZIGrm1VBB43v2WkyZwBMbI/6EQrcRkkIphPtG6bwQfaKVH+CfCH3Ekohp9CU1OWatRmCEl1pHktkQDsOIOVaUNUjeuVULuTf9ifXmTK/Bjg71RBoLakDPVms8z2R0nfuH3bz/oDjbx7UwIIE/7TXhyajL2GyP0yluuoy/SabSEKqulUdF6q1ToJH3LNzCViqm74fsIuWaxvmsr4uqRwqr6OJBo+J6gCtx1JPscADaBP9KLCfoE1r0xZ2QGN5djSdTZ1IRxVw4Qbhw+1q11XsOJi4Yn/6+SF3B73qH1rwxk0VxWqE/0dRyD/Cjbhb23K97ZVe1jeGcor+Ppy+lCUrqOASIC7nR5M1+M7SLqNIdPfoqsclWU7CBnzhPCRdLn3zvafY6EOVSVOTdGB5arwq5m2hTZm5/WoAOOED8q5Yl+Nxl/VHuif4yr4rntrEt8oViXLl4zljotWcwWn3PhW5dsscjIzWZxoMf7Zhb53gefT2sgnK3/Ow/BNjyh23krBRzXtRZ/GdgN7vTghrCoBSNzGA=}
